/*
 * JInformation.java
 *
 * Created on 26 Αύγουστος 2005, 5:42 μμ
 *
 * This file is part of __PROJECTNAME__.
 *
 * __PROJECTNAME__ is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 *
 * __PROJECTNAME__ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with __PROJECTNAME__; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

package com.panayotis.jubler.information;

import static com.panayotis.jubler.i18n.I18N._;

/**
 *
 * @author  teras
 */
public class JInformation extends javax.swing.JPanel {
    
    /** Creates new form JInformation */
    public JInformation() {
        initComponents();
    }
    
    public void setFilename(String fname) { PathL.setText(fname); }
    
    public void setTitle(String title) { TitleT.setText(title); }
    public String getTitle() { return TitleT.getText(); }
    
    public void setAuthor(String author) { AuthorT.setText(author); }
    public String getAuthor() { return AuthorT.getText(); }
    
    public void setComments(String comments) { CommentsT.setText(comments); }
    public String getComments() { return CommentsT.getText(); }
    
    public void setSource(String source) { SourceT.setText(source); }
    public String getSource() { return SourceT.getText(); }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        FilePathL = new javax.swing.JLabel();
        TitleL = new javax.swing.JLabel();
        AuthorL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        PathL = new javax.swing.JLabel();
        TitleT = new javax.swing.JTextField();
        AuthorT = new javax.swing.JTextField();
        SourceT = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentsT = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 10, 0, 10)));
        FilePathL.setText(_("File path"));
        jPanel4.add(FilePathL);

        TitleL.setText(_("Title"));
        jPanel4.add(TitleL);

        AuthorL.setText(_("Author"));
        jPanel4.add(AuthorL);

        jLabel1.setText(_("Source"));
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        PathL.setToolTipText(_("The file path of this subtitle"));
        jPanel3.add(PathL);

        TitleT.setToolTipText(_("Title for this subtitle file"));
        jPanel3.add(TitleT);

        AuthorT.setToolTipText(_("Author of this subtitle file"));
        jPanel3.add(AuthorT);

        SourceT.setToolTipText(_("Original source of this subtitle file"));
        jPanel3.add(SourceT);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder(_("Comments")));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 150));
        CommentsT.setToolTipText(_("Comments about these subtitles"));
        jScrollPane1.setViewportView(CommentsT);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorL;
    private javax.swing.JTextField AuthorT;
    private javax.swing.JTextArea CommentsT;
    private javax.swing.JLabel FilePathL;
    private javax.swing.JLabel PathL;
    private javax.swing.JTextField SourceT;
    private javax.swing.JLabel TitleL;
    private javax.swing.JTextField TitleT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
