/*
 * JResizableTabs.java
 *
 * Created on June 1, 2007, 2:29 PM
 *
 * This file is part of Jubler.
 *
 * Jubler is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 *
 * Jubler is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jubler; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

package com.panayotis.jubler.options.gui;

import java.awt.BorderLayout;
import java.awt.Insets;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author  teras
 */
public class JResizableTabs extends JPanel {
    
    private ArrayList<TabPage> tabs;
    private ArrayList<JToggleButton> buttons;
    private Window parent;
    
    /** Creates new form JResizableTabs */
    public JResizableTabs(Window parent) {
        initComponents();
        tabs = new ArrayList<TabPage>();
        buttons = new ArrayList<JToggleButton>();
        this.parent = parent;
    }
    
    public void addTab(TabPage page) {
        tabs.add(page);
        
        JToggleButton cb = new JToggleButton(page.getTabName(), page.getTabIcon());
        cb.setToolTipText(page.getTabTooltip());
        cb.setMargin(new Insets(8,8,8,8));
        TabsBG.add(cb);
        TabsSelector.add(cb);
        
        cb.addActionListener(new ActionListener() {
            private final int id = tabs.size()-1;
            
            public void actionPerformed(ActionEvent e) {
                updateTab(id);
            }
        });
        
        buttons.add(cb);
    }
    
    public ArrayList<TabPage> getTabArray() {
        return tabs;
    }
    
    public void updateTab(int id) {
        ViewP.removeAll();
        ViewP.add(tabs.get(id).getTabPanel(), BorderLayout.CENTER);
        buttons.get(id).setSelected(true);
        parent.pack();
        parent.setLocationRelativeTo(null);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        TabsBG = new javax.swing.ButtonGroup();
        TabsSelector = new javax.swing.JPanel();
        ViewP = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        TabsSelector.setLayout(new java.awt.GridLayout());

        TabsSelector.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(TabsSelector, java.awt.BorderLayout.NORTH);

        ViewP.setLayout(new java.awt.BorderLayout());

        ViewP.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 0, 8));
        add(ViewP, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TabsBG;
    private javax.swing.JPanel TabsSelector;
    private javax.swing.JPanel ViewP;
    // End of variables declaration//GEN-END:variables
    
}
