/*
 * JUnsaved.java
 *
 * Created on 9 Φεβρουάριος 2006, 10:52 μμ
 *
 * This file is part of Jubler.
 *
 * Jubler is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 *
 * Jubler is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jubler; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

package com.panayotis.jubler.options.gui;

import static com.panayotis.jubler.i18n.I18N._;

import java.util.Vector;
import javax.swing.JList;

/**
 *
 * @author  teras
 */
public class JUnsaved extends javax.swing.JPanel {
    Vector<String> unsaved;
    
    /** Creates new form JUnsaved */
    public JUnsaved(Vector<String> un) {
        unsaved = un;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UnsavedL = new JList(unsaved);

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText(_("The following files are unsaved:"));
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setText(_("Do you want to quit without saving?"));
        add(jLabel2, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setViewportView(UnsavedL);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList UnsavedL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
