/*
 * (c) 2005-2023 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package  com.panayotis.jubler.tools;

import static com.panayotis.jubler.i18n.I18N.__;

public class ReparentGUI extends javax.swing.JPanel {

    /**
     * Creates new form JSplit
     */
    public ReparentGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Position = new javax.swing.ButtonGroup();
        JubSelector = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        JubSelector.setToolTipText(__("The new parent subtitles file"));
        add(JubSelector, java.awt.BorderLayout.CENTER);

        jLabel1.setText(__("Provide the desired parent for this subtitles file"));
        add(jLabel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JComboBox JubSelector;
    private javax.swing.ButtonGroup Position;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
