/*
 * (c) 2005-2023 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package  com.panayotis.jubler.tools;

import javax.swing.JPanel;
import static com.panayotis.jubler.i18n.I18N.__;

public class RounderGUI extends JPanel {

    public RounderGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PrecS = new javax.swing.JSlider();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 1));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText(__("Number of decimals")+"      ");
        add(jLabel1, java.awt.BorderLayout.WEST);

        PrecS.setMajorTickSpacing(1);
        PrecS.setMaximum(2);
        PrecS.setPaintLabels(true);
        PrecS.setPaintTicks(true);
        PrecS.setSnapToTicks(true);
        PrecS.setToolTipText(__("Decimal digits"));
        add(PrecS, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JSlider PrecS;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
