#!/bin/sh

DEST=../../dist/i18n

rm -rf $DEST
mkdir -p $DEST
for i in *.po ; do
	LNG=`echo $i | sed -e 's/\.po$//g'`
	echo Creating class for language \"$LNG\"
	rm -rf com
	JAVAC=javac msgfmt -d . --java2 --resource=com.panayotis.jubler.i18n.Messages_$LNG $i
	if [ $? != 0 ] ; then exit 1; fi
	jar cf $DEST/$LNG.jar com
	rm -rf com
done
