/*
 * (c) 2005-2026 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

#pragma once

// Command-line help texts of the built-in tools (verbatim from the Java build).
namespace ToolHelp {
inline const char *const delete_ = "Deletes selected subtitles from the subtitle file based on time range, mark color, or style.\nThis tool permanently removes subtitle entries that match the specified criteria. Use with caution as deleted subtitles cannot be recovered. Useful for removing unwanted content, cleaning up subtitle files, or extracting specific segments by deleting everything else.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name";
inline const char *const fix = "Fix subtitle timing inconsistencies by adjusting duration, gaps, and overlaps to improve readability.\nThis comprehensive tool addresses common subtitle timing problems including too-short or too-long display times, overlapping subtitles, and insufficient gaps between entries. It can enforce reading speed limits using characters-per-second constraints and automatically resolve temporal conflicts using various strategies.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name\n  mintime=seconds - Minimum subtitle duration in seconds (decimal)\n  maxtime=seconds - Maximum subtitle duration in seconds (decimal)\n  maxcps=number - Fastest reading rate in characters per second: sets the minimum duration (characters / maxcps) unless mintime is given\n  mincps=number - Slowest reading rate in characters per second: sets the maximum duration (characters / mincps) unless maxtime is given\n  overlap=strategy - Overlap fixing strategy (distribute, divide, shift)\n  gap=seconds - Minimum gap between subtitles in seconds (decimal)";
inline const char *const jointext = "Joins consecutive subtitle entries into a single entry, combining text and extending duration.\nThis tool merges multiple subtitle entries into one by concatenating their text content with line breaks and adjusting the timing to span from the start of the first entry to the end of the last entry. Useful for combining related dialogue or reducing the number of subtitle entries for better flow.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name";
inline const char *const mark = "Mark subtitles with specified color tags for logical grouping and batch processing.\nThis tool applies color marks to subtitle entries as a practical way to categorize and group related subtitles together. Marked subtitles can then be easily selected for batch operations using other tools with the 'bymark' parameter. The marking system supports multiple colors to create different logical groups for complex subtitle processing workflows.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name\n  mark=color - Color to mark subtitles with (none, pink, yellow, cyan, orange, lightgreen, or index 0-5)";
inline const char *const recode = "Recode subtitle timing by applying scaling and center point transformation to correct frame rate differences.\nThis tool is essential when converting subtitles between different video frame rates (e.g., PAL to NTSC) or when fixing timing issues that occur linearly throughout the subtitle file. You can either specify source and target frame rates for automatic calculation, or manually define a scaling factor and center point.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name\n  center=seconds - Center point for scaling in seconds (decimal)\n  factor=number - Scaling factor (1.0 = no change, >1.0 = stretch, <1.0 = compress)\n  fromfps=number - Source frame rate\n  tofps=number - Target frame rate";
inline const char *const round = "Round subtitle timing values to specified precision to reduce file size and improve compatibility.\nThis tool rounds both start and end times of subtitle entries to a specified number of decimal places, eliminating unnecessary precision that may cause issues with some players or formats. Useful for cleaning up timing data imported from other tools or ensuring consistent precision.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name\n  decimals=number - Number of decimal places for rounding (0-3)";
inline const char *const shift = "Shift subtitle timing by adding or subtracting a fixed time offset to all selected subtitles.\nThis tool moves all subtitle entries forward or backward in time by the specified amount, maintaining the relative timing between subtitles. Useful for correcting synchronization issues when the entire subtitle track is consistently early or late compared to the video.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name\n  delta=seconds - Time offset in seconds (decimal, positive or negative)";
inline const char *const splittext = "Splits subtitle entries with multiple lines into separate entries, distributing timing proportionally.\nThis tool takes subtitle entries that contain multiple lines of text (separated by line breaks) and creates individual subtitle entries for each line. The original timing duration is divided equally among the new entries, so each line gets its proportional share of the display time. Useful for improving readability or meeting subtitle guidelines that prefer single-line entries.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name";
inline const char *const style = "Apply specified style to subtitles for formatting control.\nThis tool assigns a style definition to selected subtitle entries, controlling their visual appearance including font, size, color, position, and other formatting attributes. Styles are particularly important for advanced subtitle formats like SubStation Alpha (SSA/ASS) that support rich formatting.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name\n  style=style_name - Style name to apply to selected subtitles";
inline const char *const join = "Joins subtitle files by appending one file to another with time adjustment.\nThis tool combines two subtitle files into a single file, automatically adjusting the timing of the appended file so it begins after the current file ends, with an optional gap between them. Useful for creating multi-part subtitle files or combining episodes into a single subtitle track.\nParameters:\n  gap=time - Gap in seconds (decimal) between the two files\n  append=filename - Subtitle file to append to the current file";
inline const char *const split = "Splits subtitle files at specified time into two separate files.\nThis tool divides a single subtitle file into two parts at a given time point, with the first part containing all subtitles before the split time and the second part containing all subtitles from the split time onward (with timing adjusted to start from zero). Useful for creating separate subtitle files for multi-part videos or extracting specific segments.\nParameters:\n  at=time - Time in seconds (decimal) where to split the file\n  target=filename - Output filename for the second part";
inline const char *const sync = "Synchronize subtitles with another subtitle file by copying timing and/or text.\nThis tool aligns the current subtitle file with a reference subtitle file, allowing you to copy precise timing information, text content, or both from the source file.\nParameters:\n  start=time - Start time in seconds (decimal)\n  end=time - End time in seconds (decimal)\n  alsomark=color - Mark affected subtitles with color (none, pink, yellow, cyan, orange, lightgreen)\n  bymark=color - Select by mark color (none, pink, yellow, cyan, orange, lightgreen)\n  bystyle=style - Select by specific style name\n  sourcesub=filepath - Source subtitle file to synchronize with\n  offset=seconds - Offset in subtitle indices (positive or negative)\n  timestamp=true/false - Copy timing information from source\n  text=true/false - Copy text content from source";
inline const char *const add = "Add a new subtitle entry with specified timing and text content.\nThis tool creates a new subtitle entry with the given start time, end time, and text content. The text supports HTML-like formatting tags for styling (italic, bold, underline, colors, etc.). The new subtitle is automatically inserted at the correct chronological position in the subtitle list. Useful for adding missing dialogue, captions, or annotations to existing subtitle files.\nParameters:\n  start=time - Start time in seconds (decimal, required)\n  end=time - End time in seconds (decimal, required)\n  text=content - Subtitle text with optional HTML-like tags (required)\n  style=name - Style/theme name (optional, defaults to first available style)\n  mark=color - Mark color (optional: none, pink, yellow, cyan, orange, lightgreen)";
inline const char *const sort = "Sort subtitles by start time within a specified time range.\nThis tool reorders subtitle entries chronologically by their start times within the given time range. All subtitles within the specified time range are extracted, sorted by start time, and reinserted at the correct position. Subtitles outside the time range remain unchanged. Useful for fixing subtitle order after manual editing or merging operations.\nParameters:\n  start=time - Start time in seconds (decimal, optional - defaults to 0)\n  end=time - End time in seconds (decimal, optional - defaults to end of file)\nNote: If no time range is specified, all subtitles will be sorted.";
}  // namespace ToolHelp
