/*
 * (c) 2005-2023 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package com.panayotis.jubler.tools.replace;

import javax.swing.*;

import static com.panayotis.jubler.i18n.I18N.__;

public class JReplaceList extends javax.swing.JPanel {

    ReplaceModel model;

    /**
     * Creates new form JReplaceList
     */
    public JReplaceList() {
        initComponents();
        model = new ReplaceModel();
        TTable.setModel(model);
        TTable.getColumnModel().getColumn(0).setMaxWidth(40);
        TTable.getColumnModel().getColumn(1).setCellEditor(model.liveEditorFor(TTable));
        TTable.getColumnModel().getColumn(2).setCellEditor(model.liveEditorFor(TTable));
        TTable.getColumnModel().getColumn(3).setMaxWidth(40);
        TTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        MarkAll = new javax.swing.JButton();
        ClearAll = new javax.swing.JButton();
        Inverse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 200));
        jScrollPane1.setViewportView(TTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        MarkAll.setText(__("Select All"));
        MarkAll.setToolTipText(__("Use all above replacing scenarios"));
        MarkAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkAllActionPerformed(evt);
            }
        });
        jPanel1.add(MarkAll);

        ClearAll.setText(__("Clear All"));
        ClearAll.setToolTipText(__("Use none of the above replacing scenarios"));
        ClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllActionPerformed(evt);
            }
        });
        jPanel1.add(ClearAll);

        Inverse.setText(__("Inverse"));
        Inverse.setToolTipText(__("Inverse the selection of the scenarios above"));
        Inverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InverseActionPerformed(evt);
            }
        });
        jPanel1.add(Inverse);

        add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 2));

        jLabel1.setText("★: " + __("Whether this entry is used or not"));
        jPanel2.add(jLabel1);

        jLabel2.setText(__("Pattern") + ": " + __("The RegEx pattern to use"));
        jPanel2.add(jLabel2);

        jLabel3.setText(__("Replacement") + ": " + __("The replacement text"));
        jPanel2.add(jLabel3);

        jLabel4.setText("⎋: " + __("Parse texts as Java escaped codes (i.e. unescape sequences like \\n \\t etc.)"));
        jPanel2.add(jLabel4);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void InverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InverseActionPerformed
        for (int i = 0; i < (model.size() - 1); i++)
            model.elementAt(i).usable = !model.elementAt(i).usable;
        model.fireTableDataChanged();
    }//GEN-LAST:event_InverseActionPerformed

    private void ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllActionPerformed
        for (int i = 0; i < (model.size() - 1); i++)
            model.elementAt(i).usable = false;
        model.fireTableDataChanged();
    }//GEN-LAST:event_ClearAllActionPerformed

    private void MarkAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkAllActionPerformed
        for (int i = 0; i < (model.size() - 1); i++)
            model.elementAt(i).usable = true;
        model.fireTableDataChanged();
    }//GEN-LAST:event_MarkAllActionPerformed

    public ReplaceModel getModel() {
        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearAll;
    private javax.swing.JButton Inverse;
    private javax.swing.JButton MarkAll;
    private javax.swing.JTable TTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
