/*
 * (c) 2005-2025 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package com.panayotis.jubler.subs.loader.gui;

import com.panayotis.jubler.media.MediaFile;
import com.panayotis.jubler.os.DEBUG;
import com.panayotis.jubler.os.FileCommunicator;
import com.panayotis.jubler.plugins.Availabilities;
import com.panayotis.jubler.subs.SubFile;
import com.panayotis.jubler.subs.Subtitles;
import com.panayotis.jubler.subs.loader.SubFormat;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import java.awt.*;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;

import static com.panayotis.jubler.i18n.I18N.__;
import static com.panayotis.jubler.subs.SubFile.basic_format;

public class JSubFileDialog extends javax.swing.JDialog {

    private static File lastDirectory = initializeDefaultDirectory();
    private boolean isAccepted;
    private final JFileOptions jload;
    private final JFileOptions jsave;

    public JSubFileDialog() {
        super((Frame) null, true);
        initComponents();
        chooser.setAcceptAllFileFilterUsed(false);
        jload = new JLoadOptions();
        jsave = new JSaveOptions();
    }

    private static File initializeDefaultDirectory() {
        String default_dir = FileCommunicator.getDefaultDirPath();
        File default_dir_file = new File(default_dir);
        boolean is_valid = (default_dir_file.isDirectory() && default_dir_file.canRead());
        return is_valid ? default_dir_file : new File("");
    }

    private SubFile showDialog(Frame parent, Subtitles subs, MediaFile mfile, JFileOptions jopt) {
        jopt.updateVisuals(subs, mfile);

        // Set the filter first for save dialog - this must happen before setting selected file
        if (subs == null) { // load
            // Load dialog - empty filename
            chooser.setSelectedFile(new File(lastDirectory, ""));
            addFilters(null);
        } else { // save
            chooser.setSelectedFile(subs.getSubFile().getStrippedFile());
            addFilters(subs.getSubFile().getFormat());
        }

        // Set current directory to last used directory
        chooser.setCurrentDirectory(lastDirectory);

        getContentPane().removeAll();
        getContentPane().add(chooser, BorderLayout.CENTER);
        getContentPane().add(jopt, BorderLayout.NORTH);
        pack();
        setLocationRelativeTo(parent);
        setVisible(true);

        if (!isAccepted)
            return null;

        SubFile sfile;
        try {
            File selected_file = chooser.getSelectedFile();

            if (subs == null) // Load
                sfile = new SubFile(selected_file, SubFile.EXTENSION_GIVEN);
            else {   // Save
                sfile = new SubFile(subs.getSubFile());
                sfile.setFile(selected_file);
            }

            sfile.setFormat(findFormat(true));

            jopt.applyOptions(sfile);
            if (subs != null) // Only in Save
                sfile.updateFileByType();

            // Remember the current directory for next time
            File currentDir = chooser.getCurrentDirectory();
            // If it's a file, get its parent directory
            if (currentDir.isFile()) {
                currentDir = currentDir.getParentFile();
            }
            lastDirectory = currentDir;
            FileCommunicator.setDefaultDir(currentDir);
        } catch (Exception ex) {
            sfile = new SubFile();
        }
        return sfile;
    }

    private SubFormat findFormat(boolean newInstance) {
        JFileFilter flt = (JFileFilter) chooser.getFileFilter();
        if (flt != null) {
            SubFormat format_handler = flt.getFormatHandler();
            if (format_handler != null)
                return newInstance ? format_handler.newInstance() : format_handler;
        }
        return basic_format;
    }

    public SubFile getSaveFile(Frame parent, Subtitles subs, MediaFile mfile) {
        setTitle(__("Save Subtitles"));
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        // Don't set selected file here - let showDialog do it after setting the filter
        return showDialog(parent, subs, mfile, jsave);
    }

    public SubFile getLoadFile(Frame parent, MediaFile mfile) {
        setTitle(__("Load Subtitles"));
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        return showDialog(parent, null, mfile, jload);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();

        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
        isAccepted = evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION);

        // Check if file exists when saving and ask for confirmation
        if (isAccepted && chooser.getDialogType() == JFileChooser.SAVE_DIALOG) {
            File selectedFile = chooser.getSelectedFile();
            if (selectedFile == null)
                return;

            File fileToCheck = selectedFile;
            String extension = findFormat(false).getExtension();
            String fileName = selectedFile.getName();

            if (extension != null && !fileName.toLowerCase().endsWith("." + extension.toLowerCase())) {
                // File doesn't have the correct extension, append it
                fileToCheck = new File(selectedFile.getParentFile(), fileName + "." + extension);
            }

            if (fileToCheck.exists()) {
                int result = JOptionPane.showConfirmDialog(
                        this,
                        __("File already exists. Do you want to overwrite it?"),
                        __("Confirm Overwrite"),
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (result != JOptionPane.YES_OPTION) {
                    isAccepted = false;
                    return; // Don't close the dialog, let user choose a different file
                }
            }
        }

        setVisible(false);
    }//GEN-LAST:event_chooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser chooser;
    // End of variables declaration//GEN-END:variables

    private JFileFilter makeFilter(SubFormat format) {
        String desc = format.getDescription();
        String ext = format.getExtension();
        return new JFileFilter(ext, desc, format);
    }

    public boolean setFilters(FileFilter[] list) {
        boolean ok = false;
        try {
            for (int i = 0; i < list.length; i++) {
                FileFilter fl = list[i];
                boolean is_first_item = (i == 0);
                if (is_first_item)
                    chooser.setFileFilter(fl);
                else
                    chooser.addChoosableFileFilter(fl);//end if
            }//end for(int i=0; i < list.length; i++)
        } catch (Exception ex) {
            DEBUG.logger.log(Level.WARNING, ex.toString());
        }
        return ok;
    }//public setFilters(FileFilter[] list)

    public boolean setFilters(Vector<FileFilter> list) {
        boolean ok = false;
        try {
            int len = list.size();
            FileFilter[] array = list.toArray(new FileFilter[len]);
            ok = this.setFilters(array);
        } catch (Exception ex) {
            DEBUG.logger.log(Level.WARNING, ex.toString());
        }
        return ok;
    }//end public boolean setFilters(FileFilter[] list)

    public boolean setFilters(SubFormat[] format_list) {
        boolean ok = false;
        Vector<FileFilter> vector = new Vector<FileFilter>();
        try {
            for (int i = 0; i < format_list.length; i++) {
                SubFormat format = format_list[i];
                JFileFilter filter = makeFilter(format);
                vector.add(filter);
            }//end for(SubFormat format: format_list)
            ok = this.setFilters(vector);
        } catch (Exception ex) {
            DEBUG.logger.log(Level.WARNING, ex.toString());
        }
        return ok;
    }//end public boolean setFilter()

    public boolean setFilter(SubFormat format) {
        boolean ok = false;
        try {
            JFileFilter filter = makeFilter(format);
            chooser.setFileFilter(filter);
            ok = true;
        } catch (Exception ex) {
            DEBUG.logger.log(Level.WARNING, ex.toString());
        }
        return ok;
    }//end public boolean setFilter(SubFormat format)

    private boolean addFilters(SubFormat target) {
        try {
            ArrayList<SubFormat> formats = Availabilities.formats.getFormats();
            if (target != null) {
                formats.removeIf(f -> f.getName().equals(target.getName()));
                formats.add(0, target);
            }
            formats.forEach(it -> chooser.addChoosableFileFilter(makeFilter(it)));
            return true;
        } catch (Exception ignored) {
            return false;
        }
    }//end public boolean addFilters(ArrayList<SubFormat> format_list)

    public JFileFilter findFileFiler(SubFormat format) {
        JFileFilter found_filter = null;
        try {
            FileFilter[] filter_list = chooser.getChoosableFileFilters();
            for (FileFilter flt : filter_list) {
                found_filter = (JFileFilter) flt;
                SubFormat fmt = found_filter.getFormatHandler();
                boolean is_found = ((format == fmt)
                        || (format.getDescription() + format.getExtension()).equals(
                        (fmt.getDescription() + fmt.getExtension())));
                if (is_found)
                    break;//end if (is_found)
            }//end for (FileFilter flt : filter_list)
        } catch (Exception ex) {
        }
        return found_filter;
    }//end public JFileFilter findFileFiler(SubFormat format)
}
