/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.panayotis.jubler.options;

import com.panayotis.jubler.plugins.Theme;

import javax.swing.*;

import static com.panayotis.jubler.JublerApp.SCALING_FACTOR;
import static com.panayotis.jubler.JublerApp.prefs;
import static com.panayotis.jubler.i18n.I18N.__;

/**
 * @author teras
 */
public class JUiOptions extends JPanel implements OptionsHolder {
    private double scaling;

    /**
     * Creates new form JExternalToolsOptions
     */
    public JUiOptions(double scaling) {
        initComponents();
        if (scaling > 0.1)
            scalingFactorT.setText(Double.toString(scaling));
        this.scaling = scaling;
    }

    @Override
    public void loadPreferences() {
        prefs.getDouble(SCALING_FACTOR, scaling);
    }

    @Override
    public void savePreferences() {
        try {
            scaling = Double.parseDouble(scalingFactorT.getText());
            prefs.putDouble(SCALING_FACTOR, scaling);
        } catch (Exception ignored) {
        }
    }

    @Override
    public JPanel getTabPanel() {
        return this;
    }

    @Override
    public String getTabName() {
        return "UI Configuration";
    }

    @Override
    public String getTabTooltip() {
        return "Configure UI related parameters";
    }

    @Override
    public Icon getTabIcon() {
        return Theme.loadIcon("uioptions.png");
    }

    @Override
    public void changeProgram() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8));
        jPanel5 = new javax.swing.JPanel();
        scalingFactorT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(filler1);

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(scalingFactorT, java.awt.BorderLayout.CENTER);

        jLabel2.setText(__("Scaling factor"));
        jPanel5.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel2.add(jPanel5);

        add(jPanel2, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField scalingFactorT;
    // End of variables declaration//GEN-END:variables
}

