/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.panayotis.jubler.options;

import com.panayotis.jubler.os.UIUtils;
import com.panayotis.jubler.theme.Theme;

import javax.swing.*;

import static com.panayotis.jubler.i18n.I18N.__;

/**
 * @author teras
 */
public class JUiOptions extends JPanel implements OptionsHolder {
    private float oldScaling = Float.POSITIVE_INFINITY;

    /**
     * Creates new form JExternalToolsOptions
     */
    public JUiOptions() {
        initComponents();
        loadPreferences();
    }

    @Override
    public void loadPreferences() {
        float scaling = UIUtils.loadScaling();
        if (oldScaling == Float.POSITIVE_INFINITY)
            oldScaling = scaling;
        if (scaling > 0.1)
            scalingFactorT.setText(Double.toString(scaling));
    }

    @Override
    public void savePreferences() {
        try {
            float newScaling = Float.parseFloat(scalingFactorT.getText());
            UIUtils.saveScaling(newScaling);
            if (Math.abs(newScaling - oldScaling) > 0.1)
                JOptionPane.showMessageDialog(null, __("New scaling will be performed after you restart Jubler"));
        } catch (Exception ignored) {
        }
    }

    @Override
    public JPanel getTabPanel() {
        return this;
    }

    @Override
    public String getTabName() {
        return "UI Options";
    }

    @Override
    public String getTabTooltip() {
        return "Configure UI related parameters";
    }

    @Override
    public Icon getTabIcon() {
        return Theme.loadIcon("uioptions.png");
    }

    @Override
    public void changeProgram() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8));
        jPanel5 = new javax.swing.JPanel();
        scalingFactorT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(filler1);

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(scalingFactorT, java.awt.BorderLayout.CENTER);

        jLabel2.setText(__("Scaling factor"));
        jPanel5.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel2.add(jPanel5);

        add(jPanel2, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField scalingFactorT;
    // End of variables declaration//GEN-END:variables
}

