/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JSubFileDialog.java
 *
 * Created on Dec 21, 2008, 10:57:59 AM
 */
package com.panayotis.jubler.subs.loader.gui;

import static com.panayotis.jubler.i18n.I18N._;

import com.panayotis.jubler.media.MediaFile;
import com.panayotis.jubler.os.FileCommunicator;
import com.panayotis.jubler.subs.Subtitles;
import com.panayotis.jubler.subs.loader.SubFileFilter;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author teras
 */
public class JSubFileDialog extends javax.swing.JDialog {

    private boolean isAccepted;
    private JFileOptions jload;
    private JFileOptions jsave;

    public JSubFileDialog() {
        super((Frame) null, true);
        initComponents();
        chooser.addChoosableFileFilter(new SubFileFilter());
        FileCommunicator.getDefaultDialogPath(chooser);
        jload = new JLoadOptions();
        jsave = new JSaveOptions();
    }

    private File showDialog(Frame parent, FileOptions opts, Subtitles subs, MediaFile mfile, JFileOptions jopt) {
        jopt.updateVisuals(opts, mfile, subs);
        getContentPane().removeAll();
        getContentPane().add(chooser, BorderLayout.CENTER);
        getContentPane().add(jopt, BorderLayout.NORTH);
        pack();
        setLocationRelativeTo(parent);
        setVisible(true);
        if (!isAccepted)
            return null;
        jopt.setOptions(opts);
        opts.saveOptions();
        FileCommunicator.setDefaultDialogPath(chooser);
        return chooser.getSelectedFile();
    }

    public File getSaveFile(Frame parent, FileOptions opts, Subtitles subs, MediaFile mfile) {
        setTitle(_("Save Subtitles"));
        chooser.setSelectedFile(subs.getCurrentFile());
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        return showDialog(parent, opts, subs, mfile, jsave);
    }

    public File getLoadFile(Frame parent, FileOptions opts, MediaFile mfile) {
        setTitle(_("Load Subtitles"));
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        return showDialog(parent, opts, null, mfile, jload);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();

        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
        isAccepted = evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION);
        setVisible(false);
    }//GEN-LAST:event_chooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser chooser;
    // End of variables declaration//GEN-END:variables
}
