/*
 * (c) 2005-2023 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package  com.panayotis.jubler.media.preview;

import static com.panayotis.jubler.i18n.I18N.__;
import com.panayotis.jubler.media.MediaFile;

public class JAudioLoader extends javax.swing.JPanel {

    private MediaFile mfile;

    /**
     * Creates new form JAudioLoader
     */
    public JAudioLoader() {
        initComponents();
    }

    public void setValue(int value) {
        ProgressB.setValue(value);
    }

    public void setFilename(String fname) {
        FileL.setText(fname);
        validate();
    }

    public void updateMediaFile(MediaFile mfile) {
        this.mfile = mfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProgressB = new javax.swing.JProgressBar();
        FileL = new javax.swing.JLabel();
        AssignInterruptB = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        ProgressB.setStringPainted(true);
        jPanel1.add(ProgressB, java.awt.BorderLayout.CENTER);
        jPanel1.add(FileL, java.awt.BorderLayout.NORTH);

        AssignInterruptB.setText(__("Cancel"));
        AssignInterruptB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignInterruptBActionPerformed(evt);
            }
        });
        jPanel1.add(AssignInterruptB, java.awt.BorderLayout.EAST);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void AssignInterruptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignInterruptBActionPerformed
        if (mfile != null)
            mfile.interruptCacheCreation(true);
    }//GEN-LAST:event_AssignInterruptBActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignInterruptB;
    private javax.swing.JLabel FileL;
    private javax.swing.JProgressBar ProgressB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
