/*
 * (c) 2005-2025 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package  com.panayotis.jubler.information;

import static com.panayotis.jubler.i18n.I18N.__;

import com.panayotis.jubler.JubFrame;
import com.panayotis.jubler.media.MediaFile;
import com.panayotis.jubler.os.SystemDependent;
import com.panayotis.jubler.subs.SubAttribs;
import com.panayotis.jubler.subs.Subtitles;
import com.panayotis.jubler.subs.TotalSubMetrics;
import java.awt.BorderLayout;

import javax.swing.JDialog;

public class JInformation extends JDialog {

    private final Subtitles subs;
    private final MediaFile media;
    /* Only when the user presses OK are the changes applied; Cancel / window-close discards them. */
    private boolean accepted = false;

    /**
     * Creates new form JProperties
     *
     * @param parent
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public JInformation(JubFrame parent) {
        super(parent, true);

        subs = parent.getSubtitles();
        media = parent.getMediaFile();

        initComponents();

        SubAttribs attr = parent.getSubtitles().getAttribs();
        TitleT.setText(attr.title);
        AuthorT.setText(attr.author);
        SourceT.setText(attr.source);
        CommentsT.setText(attr.comments);

        NumberT.setText(Integer.toString(parent.getSubtitles().size()));
        TotalSubMetrics m = parent.getSubtitles().getTotalMetrics();
        TotalSubSizeT.setText(Integer.toString(m.totallength));
        TotalLinesT.setText(Integer.toString(m.totallines));
        MinSubSizeT.setText(Integer.toString(m.minlength == Integer.MAX_VALUE ? 0 : m.minlength));
        MaxSubSizeT.setText(Integer.toString(m.maxlength));
        MaxLinesT.setText(Integer.toString(m.maxlines));
        MaxLengthLineT.setText(Integer.toString(m.maxlinelength));
        MaxCPST.setText(Float.toString(m.maxcps));
        MinCPST.setText(Float.toString(m.mincps));

        // Quality Control tab data
        MinLinesT.setText(Integer.toString(m.minlines == Integer.MAX_VALUE ? 0 : m.minlines));
        MinCharPerLineT.setText(Integer.toString(m.minlinelength == Integer.MAX_VALUE ? 0 : m.minlinelength));
        MaxCharPerLineT.setText(Integer.toString(m.maxlinelength));
        MinCPMT.setText(Float.toString(m.mincpm == Float.MAX_VALUE ? 0 : m.mincpm));
        MaxCPMT.setText(Float.toString(m.maxcpm));
        MinFillPercentT.setText(Integer.toString(m.minfillpercent == Integer.MAX_VALUE ? 0 : m.minfillpercent) + "%");
        MaxFillPercentT.setText(Integer.toString(m.maxfillpercent) + "%");
        MinDurationT.setText(Float.toString(m.minduration == Float.MAX_VALUE ? 0 : m.minduration) + "s");
        MaxDurationT.setText(Float.toString(m.maxduration) + "s");

        VSelectorP.add(parent.getMediaFile().videoselector, BorderLayout.CENTER);
        // Encoding, FPS and format now live solely on the post-load bar (toggled from the toolbar),
        // so they are no longer duplicated here.

        javax.swing.JButton cancelB = new javax.swing.JButton(__("Cancel"));
        cancelB.addActionListener(e -> {
            accepted = false;
            setVisible(false);
        });
        jPanel5.add(cancelB, 0);   // to the left of OK

        pack();
        setLocationRelativeTo(parent);
    }

    /** True only if the user confirmed with OK; false on Cancel or window close. */
    public boolean isAccepted() {
        return accepted;
    }

    public SubAttribs getAttribs() {
        return new SubAttribs(TitleT.getText(), AuthorT.getText(), SourceT.getText(), CommentsT.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTabs = new javax.swing.JTabbedPane();
        InfoP = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentsT = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TitleL = new javax.swing.JLabel();
        AuthorL = new javax.swing.JLabel();
        SourceL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TitleT = new javax.swing.JTextField();
        AuthorT = new javax.swing.JTextField();
        SourceT = new javax.swing.JTextField();
        MediaP = new javax.swing.JPanel();
        VSelectorP = new javax.swing.JPanel();
        SubFileInfoP = new javax.swing.JPanel();
        StatsP = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        NumberL = new javax.swing.JLabel();
        NumberT = new javax.swing.JLabel();
        TotalSubSizeL = new javax.swing.JLabel();
        TotalSubSizeT = new javax.swing.JLabel();
        TotalLinesL = new javax.swing.JLabel();
        TotalLinesT = new javax.swing.JLabel();
        MaxSubSizeL = new javax.swing.JLabel();
        MaxSubSizeT = new javax.swing.JLabel();
        MaxLinesL = new javax.swing.JLabel();
        MaxLinesT = new javax.swing.JLabel();
        MaxLengthLineL = new javax.swing.JLabel();
        MaxLengthLineT = new javax.swing.JLabel();
        MaxCPSL = new javax.swing.JLabel();
        MaxCPST = new javax.swing.JLabel();
        MinCPSL = new javax.swing.JLabel();
        MinCPST = new javax.swing.JLabel();
        MinSubSizeL = new javax.swing.JLabel();
        MinSubSizeT = new javax.swing.JLabel();
        MinLinesL = new javax.swing.JLabel();
        MinLinesT = new javax.swing.JLabel();
        MinCharPerLineL = new javax.swing.JLabel();
        MinCharPerLineT = new javax.swing.JLabel();
        MaxCharPerLineL = new javax.swing.JLabel();
        MaxCharPerLineT = new javax.swing.JLabel();
        MinCPML = new javax.swing.JLabel();
        MinCPMT = new javax.swing.JLabel();
        MaxCPML = new javax.swing.JLabel();
        MaxCPMT = new javax.swing.JLabel();
        MinFillPercentL = new javax.swing.JLabel();
        MinFillPercentT = new javax.swing.JLabel();
        MaxFillPercentL = new javax.swing.JLabel();
        MaxFillPercentT = new javax.swing.JLabel();
        MinDurationL = new javax.swing.JLabel();
        MinDurationT = new javax.swing.JLabel();
        MaxDurationL = new javax.swing.JLabel();
        MaxDurationT = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        OKB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(__("Project Properties"));
        setResizable(false);

        PTabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PTabsStateChanged(evt);
            }
        });

        InfoP.setName("info"); // NOI18N
        InfoP.setOpaque(false);
        InfoP.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(SystemDependent.getBorder(__("Comments")));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 150));
        jPanel2.setLayout(new java.awt.BorderLayout());

        CommentsT.setToolTipText(__("Comments about these subtitles"));
        jScrollPane1.setViewportView(CommentsT);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        InfoP.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        TitleL.setText(__("Title"));
        jPanel4.add(TitleL);

        AuthorL.setText(__("Author"));
        jPanel4.add(AuthorL);

        SourceL.setText(__("Source"));
        jPanel4.add(SourceL);

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        TitleT.setToolTipText(__("Title for this subtitle file"));
        jPanel3.add(TitleT);

        AuthorT.setToolTipText(__("Author of this subtitle file"));
        jPanel3.add(AuthorT);

        SourceT.setToolTipText(__("Original source of this subtitle file"));
        jPanel3.add(SourceT);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        InfoP.add(jPanel1, java.awt.BorderLayout.NORTH);

        PTabs.addTab(__("Information"), InfoP);

        MediaP.setName("media"); // NOI18N
        MediaP.setOpaque(false);
        MediaP.setLayout(new java.awt.BorderLayout());

        VSelectorP.setOpaque(false);
        VSelectorP.setLayout(new java.awt.BorderLayout());

        SubFileInfoP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 8, 0));
        SubFileInfoP.setOpaque(false);
        SubFileInfoP.setLayout(new java.awt.BorderLayout());

        VSelectorP.add(SubFileInfoP, java.awt.BorderLayout.NORTH);

        MediaP.add(VSelectorP, java.awt.BorderLayout.NORTH);

        PTabs.addTab(__("Media"), MediaP);

        StatsP.setName("stats"); // NOI18N
        StatsP.setOpaque(false);
        StatsP.setLayout(new java.awt.BorderLayout());

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(0, 2, 0, 4));

        NumberL.setText(__("Number of subtitles"));
        jPanel8.add(NumberL);
        jPanel8.add(NumberT);

        TotalSubSizeL.setText(__("Total subtitle characters"));
        jPanel8.add(TotalSubSizeL);
        jPanel8.add(TotalSubSizeT);

        TotalLinesL.setText(__("Total subtitle lines"));
        jPanel8.add(TotalLinesL);
        jPanel8.add(TotalLinesT);

        MinSubSizeL.setText(__("Minimum subtitle length"));
        jPanel8.add(MinSubSizeL);
        jPanel8.add(MinSubSizeT);

        MaxSubSizeL.setText(__("Maximum subtitle length"));
        jPanel8.add(MaxSubSizeL);
        jPanel8.add(MaxSubSizeT);

        MinLinesL.setText(__("Minimum subtitle lines"));
        jPanel8.add(MinLinesL);
        jPanel8.add(MinLinesT);

        MaxLinesL.setText(__("Maximum subtitle lines"));
        jPanel8.add(MaxLinesL);
        jPanel8.add(MaxLinesT);

        MinCharPerLineL.setText(__("Minimum characters per line"));
        jPanel8.add(MinCharPerLineL);
        jPanel8.add(MinCharPerLineT);

        MaxLengthLineL.setText(__("Maximum characters per line"));
        jPanel8.add(MaxLengthLineL);
        jPanel8.add(MaxLengthLineT);

        MinCPSL.setText(__("Minimum subtitle characters per second"));
        jPanel8.add(MinCPSL);
        jPanel8.add(MinCPST);

        MaxCPSL.setText(__("Maximum subtitle characters per second"));
        jPanel8.add(MaxCPSL);
        jPanel8.add(MaxCPST);

        MinCPML.setText(__("Minimum characters per minute"));
        jPanel8.add(MinCPML);
        jPanel8.add(MinCPMT);

        MaxCPML.setText(__("Maximum characters per minute"));
        jPanel8.add(MaxCPML);
        jPanel8.add(MaxCPMT);

        MinFillPercentL.setText(__("Minimum fill percentage"));
        jPanel8.add(MinFillPercentL);
        jPanel8.add(MinFillPercentT);

        MaxFillPercentL.setText(__("Maximum fill percentage"));
        jPanel8.add(MaxFillPercentL);
        jPanel8.add(MaxFillPercentT);

        MinDurationL.setText(__("Minimum duration"));
        jPanel8.add(MinDurationL);
        jPanel8.add(MinDurationT);

        MaxDurationL.setText(__("Maximum duration"));
        jPanel8.add(MaxDurationL);
        jPanel8.add(MaxDurationT);

        jPanel9.add(jPanel8, java.awt.BorderLayout.NORTH);

        StatsP.add(jPanel9, java.awt.BorderLayout.NORTH);

        PTabs.addTab(__("Statistics"), StatsP);

        getContentPane().add(PTabs, java.awt.BorderLayout.CENTER);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        OKB.setText(__("OK"));
        OKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBActionPerformed(evt);
            }
        });
        jPanel5.add(OKB);

        getContentPane().add(jPanel5, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PTabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PTabsStateChanged
        if (PTabs.getSelectedComponent().getName().equals("media"))
            media.guessMediaFiles(subs);
    }//GEN-LAST:event_PTabsStateChanged

    private void OKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBActionPerformed
        accepted = true;
        setVisible(false);
    }//GEN-LAST:event_OKBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorL;
    private javax.swing.JTextField AuthorT;
    private javax.swing.JTextArea CommentsT;
    private javax.swing.JPanel InfoP;
    private javax.swing.JLabel MaxCPSL;
    private javax.swing.JLabel MaxCPST;
    private javax.swing.JLabel MaxLengthLineL;
    private javax.swing.JLabel MaxLengthLineT;
    private javax.swing.JLabel MaxLinesL;
    private javax.swing.JLabel MaxLinesT;
    private javax.swing.JLabel MaxSubSizeL;
    private javax.swing.JLabel MaxSubSizeT;
    private javax.swing.JPanel MediaP;
    private javax.swing.JLabel MinCPSL;
    private javax.swing.JLabel MinCPST;
    private javax.swing.JLabel NumberL;
    private javax.swing.JLabel NumberT;
    private javax.swing.JButton OKB;
    private javax.swing.JTabbedPane PTabs;
    private javax.swing.JLabel SourceL;
    private javax.swing.JTextField SourceT;
    private javax.swing.JPanel StatsP;
    private javax.swing.JPanel SubFileInfoP;
    private javax.swing.JLabel TitleL;
    private javax.swing.JTextField TitleT;
    private javax.swing.JLabel TotalLinesL;
    private javax.swing.JLabel TotalLinesT;
    private javax.swing.JLabel TotalSubSizeL;
    private javax.swing.JLabel TotalSubSizeT;
    private javax.swing.JPanel VSelectorP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel MaxCharPerLineL;
    private javax.swing.JLabel MaxCharPerLineT;
    private javax.swing.JLabel MaxCPML;
    private javax.swing.JLabel MaxCPMT;
    private javax.swing.JLabel MaxDurationL;
    private javax.swing.JLabel MaxDurationT;
    private javax.swing.JLabel MaxFillPercentL;
    private javax.swing.JLabel MaxFillPercentT;
    private javax.swing.JLabel MinCharPerLineL;
    private javax.swing.JLabel MinCharPerLineT;
    private javax.swing.JLabel MinCPML;
    private javax.swing.JLabel MinCPMT;
    private javax.swing.JLabel MinDurationL;
    private javax.swing.JLabel MinDurationT;
    private javax.swing.JLabel MinFillPercentL;
    private javax.swing.JLabel MinFillPercentT;
    private javax.swing.JLabel MinLinesL;
    private javax.swing.JLabel MinLinesT;
    private javax.swing.JLabel MinSubSizeL;
    private javax.swing.JLabel MinSubSizeT;
    // End of variables declaration//GEN-END:variables
}
