/*
 * (c) 2005-2023 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package com.panayotis.jubler.information;

import com.panayotis.jubler.JubFrame;
import com.panayotis.jubler.information.range.FloatRangeFilter;
import com.panayotis.jubler.information.range.IntRangeFilter;
import com.panayotis.jubler.options.Options;
import com.panayotis.jubler.subs.SubEntry;

import static com.panayotis.jubler.i18n.I18N.__;
import static com.panayotis.jubler.options.Options.*;

public class JQuality extends javax.swing.JDialog {

    @SuppressWarnings("OverridableMethodCallInConstructor")
    public JQuality(JubFrame parent) {
        super(parent, true);
        initComponents();
        ErrorColC.removeItemAt(0);
        ErrorColC.setSelectedIndex(getErrorColor() - 1);

        spaceCharsC.setSelected(isSpaceChars());
        newlineCharsC.setSelected(isNewlineChars());
        compactC.setSelected(isCompactSubs());
        otherCharsC.setSelected(isOtherChars());

        MaxLinesT.setText(String.valueOf(getMaxLines()));
        FillPercentT.setText(String.valueOf(getFillPercent()));
        MaxLineLengthT.setText(String.valueOf(getMaxLineLength()));
        MaxCPST.setText(String.valueOf(getMaxCPS()));
        MinDurationT.setText(String.valueOf(getMinDuration()));
        MaxDurationT.setText(String.valueOf(getMaxDuration()));

        new IntRangeFilter(1, 100, Options::setMaxLines).setDocumentFilter(MaxLinesT);
        new FloatRangeFilter(0, 100, Options::setFillPercent).setDocumentFilter(FillPercentT);
        new IntRangeFilter(1, 1000, Options::setMaxLineLength).setDocumentFilter(MaxLineLengthT);
        new IntRangeFilter(1, 1000, Options::setMaxCPS).setDocumentFilter(MaxCPST);
        new FloatRangeFilter(0, 1000, Options::setMinDuration).setDocumentFilter(MinDurationT);
        new FloatRangeFilter(0, 1000, Options::setMaxDuration).setDocumentFilter(MaxDurationT);

        pack();
        setLocationRelativeTo(parent);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        ErrorColL = new javax.swing.JLabel();
        ErrorColC = new javax.swing.JComboBox();
        jPanel13 = new javax.swing.JPanel();
        spaceCharsC = new javax.swing.JCheckBox();
        newlineCharsC = new javax.swing.JCheckBox();
        compactC = new javax.swing.JCheckBox();
        otherCharsC = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        MaxLinesL = new javax.swing.JLabel();
        MaxLinesT = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        FillPercentL = new javax.swing.JLabel();
        FillPercentT = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        MaxLineLengthL = new javax.swing.JLabel();
        MaxLineLengthT = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        MaxCPSL = new javax.swing.JLabel();
        MaxCPST = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        MinDurationL = new javax.swing.JLabel();
        MinDurationT = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        MaxDurationL = new javax.swing.JLabel();
        MaxDurationT = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        OKB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(__("Quality settings"));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 12, 0, 12));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 30));

        jPanel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.darkGray), javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0)));
        jPanel11.setLayout(new java.awt.BorderLayout());

        ErrorColL.setText(__("Color to use"));
        ErrorColL.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 12));
        jPanel11.add(ErrorColL, java.awt.BorderLayout.WEST);

        ErrorColC.setModel(new javax.swing.DefaultComboBoxModel(SubEntry.MarkNames));
        ErrorColC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorColCActionPerformed(evt);
            }
        });
        jPanel11.add(ErrorColC, java.awt.BorderLayout.CENTER);

        jPanel13.setLayout(new java.awt.GridLayout(0, 2));

        spaceCharsC.setText(__("Treat space as character"));
        spaceCharsC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceCharsCActionPerformed(evt);
            }
        });
        jPanel13.add(spaceCharsC);

        newlineCharsC.setText(__("Treat newline as character"));
        newlineCharsC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlineCharsCActionPerformed(evt);
            }
        });
        jPanel13.add(newlineCharsC);

        compactC.setSelected(true);
        compactC.setText(__("Prefer compact subtitles"));
        compactC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compactCActionPerformed(evt);
            }
        });
        jPanel13.add(compactC);

        otherCharsC.setText(__("Treat non-alphanumeric as character"));
        otherCharsC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherCharsCActionPerformed(evt);
            }
        });
        jPanel13.add(otherCharsC);

        jPanel11.add(jPanel13, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel11, java.awt.BorderLayout.NORTH);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(0, 1, 0, 16));

        jPanel15.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel14.setLayout(new java.awt.BorderLayout(12, 0));

        MaxLinesL.setText(__("Maximum number of lines per subtitle"));
        jPanel14.add(MaxLinesL, java.awt.BorderLayout.WEST);
        jPanel14.add(MaxLinesT, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel14);

        jPanel21.setLayout(new java.awt.BorderLayout(12, 0));

        FillPercentL.setText(__("Line fill percentage"));
        jPanel21.add(FillPercentL, java.awt.BorderLayout.WEST);
        jPanel21.add(FillPercentT, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel21);

        jPanel12.add(jPanel15);

        jPanel16.setLayout(new java.awt.BorderLayout(12, 0));

        MaxLineLengthL.setText(__("Maximum number of characters per line"));
        jPanel16.add(MaxLineLengthL, java.awt.BorderLayout.WEST);
        jPanel16.add(MaxLineLengthT, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel16);

        jPanel17.setLayout(new java.awt.BorderLayout(12, 0));

        MaxCPSL.setText(__("Maximum number of characters per second"));
        jPanel17.add(MaxCPSL, java.awt.BorderLayout.WEST);
        jPanel17.add(MaxCPST, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel17);

        jPanel18.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel20.setLayout(new java.awt.BorderLayout(12, 0));

        MinDurationL.setText(__("Minimum duration in seconds"));
        jPanel20.add(MinDurationL, java.awt.BorderLayout.WEST);
        jPanel20.add(MinDurationT, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel20);

        jPanel7.setLayout(new java.awt.BorderLayout(12, 0));

        MaxDurationL.setText(__("Maximum duration in seconds"));
        jPanel7.add(MaxDurationL, java.awt.BorderLayout.WEST);
        jPanel7.add(MaxDurationT, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel7);

        jPanel12.add(jPanel18);

        jPanel1.add(jPanel12, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 10));

        OKB.setText(__("OK"));
        OKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBActionPerformed(evt);
            }
        });
        jPanel5.add(OKB);

        getContentPane().add(jPanel5, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBActionPerformed
        setVisible(false);
    }//GEN-LAST:event_OKBActionPerformed

    private void ErrorColCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorColCActionPerformed
        Options.setErrorColor(ErrorColC.getSelectedIndex() + 1);
    }//GEN-LAST:event_ErrorColCActionPerformed

    private void spaceCharsCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceCharsCActionPerformed
        Options.setSpaceChars(spaceCharsC.isSelected());
    }//GEN-LAST:event_spaceCharsCActionPerformed

    private void compactCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compactCActionPerformed
        Options.setCompactSubs(compactC.isSelected());
    }//GEN-LAST:event_compactCActionPerformed

    private void newlineCharsCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlineCharsCActionPerformed
        Options.setNewlineChars(newlineCharsC.isSelected());
    }//GEN-LAST:event_newlineCharsCActionPerformed

    private void otherCharsCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherCharsCActionPerformed
        Options.setOtherChars(otherCharsC.isSelected());
    }//GEN-LAST:event_otherCharsCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ErrorColC;
    private javax.swing.JLabel ErrorColL;
    private javax.swing.JLabel FillPercentL;
    private javax.swing.JTextField FillPercentT;
    private javax.swing.JLabel MaxCPSL;
    private javax.swing.JTextField MaxCPST;
    private javax.swing.JLabel MaxDurationL;
    private javax.swing.JTextField MaxDurationT;
    private javax.swing.JLabel MaxLineLengthL;
    private javax.swing.JTextField MaxLineLengthT;
    private javax.swing.JLabel MaxLinesL;
    private javax.swing.JTextField MaxLinesT;
    private javax.swing.JLabel MinDurationL;
    private javax.swing.JTextField MinDurationT;
    private javax.swing.JButton OKB;
    private javax.swing.JCheckBox compactC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JCheckBox newlineCharsC;
    private javax.swing.JCheckBox otherCharsC;
    private javax.swing.JCheckBox spaceCharsC;
    // End of variables declaration//GEN-END:variables
}
