/*
 * (c) 2005-2025 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package  com.panayotis.jubler.options;

import com.panayotis.jubler.JublerPrefs;
import com.panayotis.jubler.os.JIDialog;
import com.panayotis.jubler.os.MissingProgram;
import static com.panayotis.jubler.i18n.I18N.__;

import java.awt.Window;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

public class JExtBasicOptions extends JPanel {

    protected String name;
    protected String descriptiveName;
    protected String family;
    private final ArrayList<String> searchname;

    /**
     * Creates new form MPlay
     */
    public JExtBasicOptions(String family, String name, String descriptiveName, ArrayList<String> searchname) {
        super();

        this.family = family;
        this.name = name;
        this.descriptiveName = descriptiveName;
        this.searchname = searchname;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrowserP = new javax.swing.JPanel();
        FilenameT = new javax.swing.JTextField();
        FileL = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        BrowserP.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 8, 0));
        BrowserP.setLayout(new java.awt.BorderLayout());

        FilenameT.setColumns(20);
        FilenameT.setToolTipText(__("The absolute path of the executable. Leave empty to auto-detect from the system path"));
        BrowserP.add(FilenameT, java.awt.BorderLayout.CENTER);

        FileL.setText(__("{0} path", descriptiveName));
        BrowserP.add(FileL, java.awt.BorderLayout.NORTH);

        add(BrowserP, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel BrowserP;
    private javax.swing.JLabel FileL;
    private javax.swing.JTextField FilenameT;
    // End of variables declaration//GEN-END:variables

    protected void loadPreferences() {
        String stored = JublerPrefs.getString(family.toLowerCase() + "." + name.toLowerCase() + ".path", "");
        if (stored.isEmpty()) {
            String detected = autoDetect();
            if (detected != null)
                stored = detected;
        }
        FilenameT.setText(stored);
    }

    protected void savePreferences() {
        JublerPrefs.set(family.toLowerCase() + "." + name.toLowerCase() + ".path", FilenameT.getText());
    }

    public String getExecFileName() {
        return FilenameT.getText();
    }

    public JPanel getOptionsPanel() {
        return this;
    }

    /* Use this method every time an update to the panel is needed */
    protected void updateOptionsPanel() {
    }

    /**
     * Refresh this panel, populate it from preferences, and show it in a modal Configure dialog; on accept the
     * new values are persisted. Lets a caller outside the options package (e.g. a tool's Configure button)
     * pop up the panel without the load/save/update hooks having to be public.
     */
    public boolean configureInDialog(Window parent, String title) {
        updateOptionsPanel();
        loadPreferences();
        if (JIDialog.action(parent, this, title)) {
            savePreferences();
            return true;
        }
        return false;
    }

    /**
     * Locate the executable: the currently configured path if it is valid,
     * otherwise the first candidate name found on the system path or in the
     * usual install directories. GUI launches (notably a macOS .app) do not
     * inherit the shell PATH, so the common bin directories are probed too.
     * @return the executable path, or null if none was found
     */
    private String autoDetect() {
        String current = FilenameT == null ? null : FilenameT.getText();
        if (current != null && !current.isEmpty() && new File(current).canExecute())
            return current;

        List<String> dirs = new ArrayList<>();
        String path = System.getenv("PATH");
        if (path != null)
            for (String dir : path.split(File.pathSeparator))
                if (!dir.isEmpty())
                    dirs.add(dir);
        dirs.add("/usr/bin");
        dirs.add("/usr/local/bin");
        dirs.add("/opt/homebrew/bin");
        dirs.add("/opt/local/bin");

        for (String dir : dirs)
            for (String candidate : searchname) {
                File f = new File(dir, candidate);
                if (f.canExecute())
                    return f.getAbsolutePath();
            }
        return null;
    }

    /**
     * Tell the user the program is missing. Subclasses override this to give
     * operating-system specific installation instructions.
     */
    protected void notifyMissing() {
        String msg = __("{0} could not be found on your system. Please install it and set its path in the preferences.", descriptiveName);
        MissingProgram.warn(name, __("{0} not found", descriptiveName), msg, "", "", "");
    }

    /**
     * Whether the executable can be located (configured path or on the system PATH / usual install
     * dirs), with no side effects — used to gate a tool's self-registration so it does not advertise
     * itself when the backing program is absent (e.g. aspell inside the Flatpak sandbox).
     */
    public boolean isAvailable() {
        return autoDetect() != null;
    }

    /**
     * Make sure the executable path is known: auto-detect it if needed, or warn
     * the user (with install instructions) when it cannot be found.
     * @return true if an executable path is available
     */
    public boolean requestExecutable() {
        String found = autoDetect();
        if (found != null) {
            FilenameT.setText(found);
            savePreferences();
            updateOptionsPanel();
            return true;
        }
        notifyMissing();
        return false;
    }
}
