/*
 * (c) 2005-2025 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package com.panayotis.jubler.options;

import com.panayotis.appenh.AFileChooser;
import com.panayotis.jubler.JubFrame;
import com.panayotis.jubler.JublerPrefs;
import com.panayotis.jubler.media.player.ExternalVideoPlayer;
import com.panayotis.jubler.options.gui.JOptionTabs;
import com.panayotis.jubler.tools.externals.AvailExternals;
import com.panayotis.jubler.tools.spell.SpellChecker;

import javax.swing.*;
import java.awt.*;
import java.io.File;

import static com.panayotis.jubler.i18n.I18N.__;

public class JPreferences extends javax.swing.JDialog {

    /* GUI element to hold various preferences
     * it is "friendly", since it is needed in Options
     */
    public JOptionTabs Tabs;
    /* Shortcuts to panels */
    private JExternalOptions jplay;
    private JExternalOptions jspell;
    private JShortcutsOptions jcut;
    private JExternalToolsOptions jext;
    private boolean dialog_status;

    private AFileChooser fileChooser;

    /**
     * Creates new form JPreferences
     */
    public JPreferences(JubFrame jub) {
        super(jub);

        Tabs = new JOptionTabs(this);
        Tabs.addTab(jplay = new JExternalOptions(new AvailExternals(ExternalVideoPlayer.family, __("Player"), "player_pref")));
        Tabs.addTab(jspell = new JExternalOptions(new AvailExternals(SpellChecker.family, __("Speller"), "spellcheck_pref")));
        Tabs.addTab(jcut = new JShortcutsOptions(jub.JublerMenuBar));
        Tabs.addTab(jext = new JExternalToolsOptions());
        Options.loadSystemPreferences(this);

        initComponents();
        add(Tabs, BorderLayout.CENTER);
        pack();
        setLocationRelativeTo(null);
    }

    public ExternalVideoPlayer getVideoPlayer() {
        return (ExternalVideoPlayer) jplay.getObject();
    }

    public SpellChecker getSpellChecker() {
        return (SpellChecker) jspell.getObject();
    }

    public void setMenuShortcuts(JMenuBar bar) {
        jcut.applyMenuShortcuts(bar);
    }

    public void showPreferencesDialog() {
        dialog_status = false;
        Options.loadSystemPreferences(this);
        Tabs.initTabs();
        setVisible(true);
        if (dialog_status)
            Options.saveSystemPreferences(this);
        else
            Options.loadSystemPreferences(this); // Make sure options are returned to their saved state
    }

    private AFileChooser getFileChooser() {
        if (fileChooser == null)
            fileChooser = new AFileChooser()
                    .mode(AFileChooser.FileSelectionMode.FilesOnly)
                    .filter("xml", __("XML files"))
                    .forceExtension(true)
                    .saveButtonTitle(__("Export"))
                    .loadButtonTitle(__("Import"));
        return fileChooser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LowerP = new javax.swing.JPanel();
        ButtonsP = new javax.swing.JPanel();
        CancelB = new javax.swing.JButton();
        AcceptB = new javax.swing.JButton();
        SavePrefsP = new javax.swing.JPanel();
        SavePrefsB = new javax.swing.JButton();
        LoadPrefsB = new javax.swing.JButton();
        ResetPrefsB = new javax.swing.JButton();

        setTitle(__("Jubler Preferences"));
        setModal(true);
        setResizable(false);

        LowerP.setLayout(new java.awt.BorderLayout());

        ButtonsP.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 6, 16));
        ButtonsP.setLayout(new java.awt.GridLayout(1, 2, 4, 0));

        CancelB.setText(__("Cancel"));
        CancelB.setToolTipText(__("Cancel changes and revert to previous values"));
        CancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBActionPerformed(evt);
            }
        });
        ButtonsP.add(CancelB);

        AcceptB.setText(__("Accept"));
        AcceptB.setToolTipText(__("Accept and save preferences"));
        AcceptB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBActionPerformed(evt);
            }
        });
        ButtonsP.add(AcceptB);

        LowerP.add(ButtonsP, java.awt.BorderLayout.EAST);

        SavePrefsP.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 16, 6, 0));
        SavePrefsP.setLayout(new java.awt.GridLayout(1, 3, 4, 0));

        SavePrefsB.setText(__("Export"));
        SavePrefsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePrefsBActionPerformed(evt);
            }
        });
        SavePrefsP.add(SavePrefsB);

        LoadPrefsB.setText(__("Import"));
        LoadPrefsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadPrefsBActionPerformed(evt);
            }
        });
        SavePrefsP.add(LoadPrefsB);

        ResetPrefsB.setText(__("Reset"));
        ResetPrefsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPrefsBActionPerformed(evt);
            }
        });
        SavePrefsP.add(ResetPrefsB);

        LowerP.add(SavePrefsP, java.awt.BorderLayout.WEST);

        getContentPane().add(LowerP, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBActionPerformed
        dialog_status = false;
        setVisible(false);
    }//GEN-LAST:event_CancelBActionPerformed

    private void AcceptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBActionPerformed
        dialog_status = true;
        setVisible(false);
    }//GEN-LAST:event_AcceptBActionPerformed

    private void LoadPrefsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadPrefsBActionPerformed
        File file = getFileChooser()
                .title(__("Import preferences"))
                .loadSingle();
        if (file != null) {
            String error = JublerPrefs.importPrefs(file);
            if (error != null)
                JOptionPane.showMessageDialog(this, error, __("Error"), JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, __("Preferences imported successfully.") + "\n" + __("Consider exiting Jubler and restarting it to apply the new preferences."), __("Success"), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_LoadPrefsBActionPerformed

    private void SavePrefsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePrefsBActionPerformed
        File file = getFileChooser()
                .title(__("Export preferences"))
                .mode(AFileChooser.FileSelectionMode.FilesOnly)
                .save();
        if (file != null) {
            String error = JublerPrefs.exportPrefs(file);
            if (error != null)
                JOptionPane.showMessageDialog(this, error, __("Error"), JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, __("Preferences exported successfully."), __("Success"), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SavePrefsBActionPerformed

    private void ResetPrefsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPrefsBActionPerformed
        int result = JOptionPane.showConfirmDialog(this,
                __("This will delete all preferences and reset them to defaults.") + "\n" +
                __("You will need to exit Jubler for the changes to take full effect.") + "\n\n" +
                __("Are you sure you want to continue?"),
                __("Reset Preferences"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            String error = JublerPrefs.resetPrefs();
            if (error != null)
                JOptionPane.showMessageDialog(this, error, __("Error"), JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(this,
                        __("All preferences have been reset to defaults.") + "\n" +
                        __("Please exit Jubler and restart it to apply the changes."),
                        __("Success"),
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ResetPrefsBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptB;
    private javax.swing.JPanel ButtonsP;
    private javax.swing.JButton CancelB;
    private javax.swing.JButton LoadPrefsB;
    private javax.swing.JPanel LowerP;
    private javax.swing.JButton ResetPrefsB;
    private javax.swing.JButton SavePrefsB;
    private javax.swing.JPanel SavePrefsP;
    // End of variables declaration//GEN-END:variables
}
