package com.panayotis.jubler.options;
/*
 * MPlay.java
 *
 * Created on 6 Ιούλιος 2005, 4:18 πμ
 * 
 * This file is part of Jubler.
 *
 * Jubler is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 *
 * Jubler is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jubler; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

import com.panayotis.jubler.os.DEBUG;
import static com.panayotis.jubler.i18n.I18N._;

import com.panayotis.jubler.options.OptionsIO;
import com.panayotis.jubler.os.SystemDependent;
import com.panayotis.jubler.os.TreeWalker;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JPanel;


/**
 *
 * @author  teras
 */
public class ExtOptions extends JPanel {
    private JFileChooser fdialog;
    
    protected String name;
    protected String programname;
    protected String type;
    
    String filename;
    
    /** Creates new form MPlay */
    public ExtOptions (String type, String name, String programname) {
        super();

        this.type = type;
        this.name = name;
        this.programname = programname;

        initComponents();
        loadOptions();
        
        FileL.setText(_("{0} path", name));
        fdialog = new JFileChooser();
        fdialog.setFileSelectionMode(JFileChooser.FILES_ONLY);
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Visuals = new javax.swing.JPanel();
        FilenameT = new javax.swing.JTextField();
        Browse = new javax.swing.JButton();
        FileL = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        Visuals.setLayout(new java.awt.BorderLayout());

        FilenameT.setColumns(20);
        FilenameT.setEditable(false);
        FilenameT.setToolTipText(_("The absolute path of the player. Use the Browse button to change it"));
        Visuals.add(FilenameT, java.awt.BorderLayout.CENTER);

        Browse.setText(_("Browse"));
        Browse.setToolTipText(_("Open a file dialog to select the filename of the player"));
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        Visuals.add(Browse, java.awt.BorderLayout.EAST);

        FileL.setText("[path]");
        Visuals.add(FileL, java.awt.BorderLayout.NORTH);

        add(Visuals, java.awt.BorderLayout.SOUTH);

    }
    // </editor-fold>//GEN-END:initComponents
    
    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        if ( fdialog.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
        FilenameT.setText(TreeWalker.getFile(fdialog.getSelectedFile().getPath(), programname));
    }//GEN-LAST:event_BrowseActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JLabel FileL;
    private javax.swing.JTextField FilenameT;
    protected javax.swing.JPanel Visuals;
    // End of variables declaration//GEN-END:variables
    
    protected void loadOptions() {
        Properties pr = OptionsIO.getPrefFile();
        FilenameT.setText( pr.getProperty(type + "." + name + ".Path", name.toLowerCase()));
        filename = FilenameT.getText();
    }
    
    public void saveOptions() {
        filename = FilenameT.getText();
        Properties pr = OptionsIO.getPrefFile();
        pr.setProperty(type + "." + name + ".Path", filename);
        OptionsIO.savePrefFile(pr);
    }

    public void resetOptions() {
        FilenameT.setText(filename);
    }
    
    public String getExecFileName() {
        return SystemDependent.getRealExecFilename(filename);
    }
}
