/*
 * JEncoding.java
 *
 * Created on 14 Απρίλιος 2008, 4:07 μμ
 */
package com.panayotis.jubler.options;

import static com.panayotis.jubler.i18n.I18N._;

import java.nio.charset.Charset;
import java.util.Iterator;
import java.util.SortedMap;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author  teras
 */
public class JEncoding extends JPanel {

    public static final String[] AvailEncodings;

    static {
        SortedMap encs = Charset.availableCharsets();
        AvailEncodings = new String[encs.size()];
        int pos;
        String item;

        pos = 0;
        for (Iterator it = encs.keySet().iterator(); it.hasNext();) {
            item = it.next().toString();
            AvailEncodings[pos++] = item;
        }
    }

    /** Creates new form JEncoding */
    public JEncoding() {
        initComponents();
    }

    public String getItemName() {
        return Encoding.getSelectedItem().toString();
    }
    
    public void setItemName(String value, String deflt) {
        Encoding.setSelectedItem(value);
        if (!Encoding.getSelectedItem().toString().equals(value))
            Encoding.setSelectedItem(deflt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encoding = new JComboBox(AvailEncodings);
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Encoding.setToolTipText(_("Select the encoding to be searched first"));
        add(Encoding, java.awt.BorderLayout.CENTER);

        jButton1.setText(_("Wizard"));
        add(jButton1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Encoding;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
