/*
 * JUnsaved.java
 *
 * Created on 9 Φεβρουάριος 2006, 10:52 μμ
 */

package com.panayotis.jubler.options;

import static com.panayotis.jubler.i18n.I18N._;

import java.util.Vector;
import javax.swing.JList;

/**
 *
 * @author  teras
 */
public class JUnsaved extends javax.swing.JPanel {
    Vector<String> unsaved;
    
    /** Creates new form JUnsaved */
    public JUnsaved(Vector<String> un) {
        unsaved = un;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UnsavedL = new JList(unsaved);

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText(_("The following files are unsaved:"));
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setText(_("Do you want to quit without saving?"));
        add(jLabel2, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setViewportView(UnsavedL);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList UnsavedL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
