/*
 * (c) 2005-2023 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package  com.panayotis.jubler.time.gui;

import com.panayotis.jubler.subs.SubEntry;
import com.panayotis.jubler.subs.Subtitles;
import java.awt.BorderLayout;
import java.util.ArrayList;

public class JTimeRegion extends JTimeArea {

    private JTimeSelector starttime, endtime;

    /**
     * Creates new form jTimeRegion
     */
    public JTimeRegion() {
        super();
        initComponents();
        add(SubCP, BorderLayout.SOUTH);

        starttime = new JTimeSelector(true);
        endtime = new JTimeSelector(false);
        TimesP.add(starttime);
        TimesP.add(endtime);
    }

    @Override
    public void setEnabled(boolean status) {
        super.setEnabled(status);
        starttime.setEnabled(status);
        endtime.setEnabled(status);
    }

    @Override
    public void updateData(Subtitles subs, int[] selected) {
        super.updateData(subs, selected);
        starttime.updateData(findFirstInList(subs, selected));
        endtime.updateData(findLastInList(subs, selected));
    }

    public ArrayList<SubEntry> getAffectedSubs() {
        /* Select affected subtitles by time region */
        double tstart, tfinish;
        double tcurrent;

        ArrayList<SubEntry> affected;
        SubEntry csub;
        int i;

        tstart = getStartTime();
        tfinish = getFinishTime();

        affected = new ArrayList<SubEntry>();
        for (i = 0; i < subs.size(); i++) {
            csub = subs.elementAt(i);
            tcurrent = csub.getStartTime().toSeconds();
            if (tcurrent >= tstart && tcurrent <= tfinish)
                affected.add(csub);
        }
        return affected;
    }

    public double getStartTime() {
        return starttime.getTime();
    }

    public double getFinishTime() {
        return endtime.getTime();
    }

    public void setRegionToMaximum() {
        starttime.setTimeToEdge();
        endtime.setTimeToEdge();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FromGroup = new javax.swing.ButtonGroup();
        ToGroup = new javax.swing.ButtonGroup();
        TimesP = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        TimesP.setOpaque(false);
        TimesP.setLayout(new java.awt.GridLayout(1, 2));
        add(TimesP, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup FromGroup;
    private javax.swing.JPanel TimesP;
    private javax.swing.ButtonGroup ToGroup;
    // End of variables declaration//GEN-END:variables
}
