/*
 * (c) 2005-2023 by Panayotis Katsaloulis
 * SPDX-License-Identifier: AGPL-3.0-only
 * This file is part of Jubler.
 */

package  com.panayotis.jubler.time.gui;

import com.panayotis.jubler.time.Time;
import java.awt.BorderLayout;

public class JTimeSingleSelection extends javax.swing.JPanel {

    private JTimeSpinner splitpos;
    private String DialogLabel;

    /**
     * Creates new form JJoin
     */
    public JTimeSingleSelection(Time t, String DialogLabel) {
        this(DialogLabel);
        setTime(t);
    }

    public JTimeSingleSelection(String DialogLabel) {
        splitpos = new JTimeSpinner();
        this.DialogLabel = DialogLabel;
        initComponents();
        ViewP.add(splitpos, BorderLayout.CENTER);
    }

    public void setToolTip(String txt) {
        splitpos.setToolTipText(txt);
    }

    public void setLabel(String txt) {
    }

    public void setTime(Time t) {
        splitpos.setValue(t);
    }

    public Time getTime() {
        return (Time) splitpos.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ViewP = new javax.swing.JPanel();
        TimeLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        ViewP.setLayout(new java.awt.BorderLayout());

        TimeLabel.setText(DialogLabel);
        ViewP.add(TimeLabel, java.awt.BorderLayout.NORTH);

        add(ViewP, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JPanel ViewP;
    // End of variables declaration//GEN-END:variables
}
