/*
 * JMarker.java
 *
 * Created on 26 Ιούνιος 2005, 12:59 πμ
 * 
 * This file is part of Jubler.
 *
 * Jubler is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 *
 * Jubler is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jubler; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

package com.panayotis.jubler.tools;
import com.panayotis.jubler.Jubler;
import com.panayotis.jubler.events.menu.tool.spell.JSpellChecker;

import static com.panayotis.jubler.i18n.I18N._;


/**
 *
 * @author  teras
 */
public class JSpeller extends JTool {
   
    public JSpeller () {
        super (true);
    }
    
    
    public void initialize() {
        initComponents();
    }
    

    protected String getToolTitle() {
        return _("Spell check");
    }

    protected void storeSelections() {
        JSpellChecker checkvisual = new JSpellChecker(jparent, Jubler.prefs.getSpellChecker(), affected_list);
        checkvisual.findNextWord();
    }
    
    /* All work has been done in JSpellChecker */
    /* We ignore default JTool for-loop */
    protected void affect(int index) {}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
