#!/bin/sh
PATH=$PATH:/usr/local/opt/gettext/bin

source ../../core/src/main/resources/com/panayotis/jubler/information/version.prop

for i in *.po ; do
	LNG=`echo $i | sed -e 's/\.po$//g'`
	echo Creating class for language \"$LNG\"
	rm -rf com
	JAVAC=javac msgfmt -d . --java2 --resource=com.panayotis.jubler.i18n.Messages_$LNG $i || exit 1
	jar cf $LNG.jar com || exit 1
    mvn install:install-file -Dfile=$LNG.jar -DgroupId=com.panayotis.jubler -DartifactId=$LNG -Dversion=$version -Dpackaging=jar || exit 1
    rm -rf com $LNG.jar
done
