#!/bin/bash
PATH=$PATH:/usr/local/opt/gettext/bin

set -x
set -e

cd `dirname $0`
pushd ../../modules/core
mvn process-resources
source target/classes/com/panayotis/jubler/information/version.prop
popd

rm -rf cache
mkdir cache

for i in *.po ; do
    LNG=`echo $i | sed -e 's/\.po$//g'`
    echo Creating class for language \"$LNG\"
    rm -rf com
    export JAVAC=`which javac`
    msgfmt -d . --java2 --resource=com.panayotis.jubler.i18n.Messages_$LNG $i
    jar cf $LNG.jar com || exit 1
    mvn install:install-file -Dfile=$LNG.jar -DgroupId=com.panayotis.jubler -DartifactId=$LNG -Dversion=$version -Dpackaging=jar
    rm -rf com
    mv $LNG.jar cache
done
