#!/bin/sh

DEST=../../dist/i18n

MSGFMT=msgfmt
if [ -f "/usr/local/opt/gettext/bin/msgfmt" ] ; then
    MSGFMT=/usr/local/opt/gettext/bin/msgfmt
fi

rm -rf $DEST
mkdir -p $DEST
for i in *.po ; do
	LNG=`echo $i | sed -e 's/\.po$//g'`
	echo Creating class for language \"$LNG\"
	rm -rf com
	JAVAC=javac ${MSGFMT} -d . --java2 --resource=com.panayotis.jubler.i18n.Messages_$LNG $i
	if [ $? != 0 ] ; then exit 1; fi
	jar cf $DEST/$LNG.jar com
	rm -rf com
done
