#!/bin/sh
PATH=$PATH:/usr/local/opt/gettext/bin

rm -f jubler.pot
cd ../..
xgettext  --from-code=utf-8 -k__ `find core plugins ../jupidator/src -name *.java` -i -o resources/i18n/jubler.pot
cd resources/i18n
