/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panayotis_jubler_preview_decoders_NativeDecoder */

#ifndef _Included_com_panayotis_jubler_preview_decoders_NativeDecoder
#define _Included_com_panayotis_jubler_preview_decoders_NativeDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panayotis_jubler_preview_decoders_NativeDecoder
 * Method:    grabCache
 * Signature: (Ljava/lang/String;DD)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_panayotis_jubler_preview_decoders_NativeDecoder_grabCache
  (JNIEnv *, jobject, jstring, jdouble, jdouble);

/*
 * Class:     com_panayotis_jubler_preview_decoders_NativeDecoder
 * Method:    forgetCache
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_panayotis_jubler_preview_decoders_NativeDecoder_forgetCache
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
